apiVersion: v1
kind: Pod
metadata:
  name: myapp 
  labels: 
    owner: dipendra
    app: myapp
spec:
  containers:
    - name: mynginx-app
      image: nginx
      ports:
        - containerPort: 80
