apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  labels:
    app: myappnew
    type: dev
    owner: dipendra
spec:
  selector:
    app: myappnew
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
  type: NodePort
